# permissions for end users to view flowtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flowtest-viewer-role
rules:
- apiGroups:
  - loggingpipelineplumber.isala.me
  resources:
  - flowtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loggingpipelineplumber.isala.me
  resources:
  - flowtests/status
  verbs:
  - get
