
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - clusterflows
  - clusteroutputs
  - flows
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - loggingplumber.isala.me
  resources:
  - flowtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loggingplumber.isala.me
  resources:
  - flowtests/finalizers
  verbs:
  - update
- apiGroups:
  - loggingplumber.isala.me
  resources:
  - flowtests/status
  verbs:
  - get
  - patch
  - update
