apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: busybox-echo
  labels:
    loggingpipelineplumber.isala.me/test: simulations
spec:
  localOutputRefs:
    - busybox-echo
  match:
    - select:
        labels:
          loggingpipelineplumber.isala.me/test: invalid
    - select:
        labels:
          loggingpipelineplumber.isala.me/test: simulations
  filters:
    - grep:
        regexp:
          - key: first
            pattern: /^5\d\d$/
    - record_modifier:
        records:
          - foo: "bar"
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: busybox-echo
  labels:
    loggingpipelineplumber.isala.me/test: simulations
spec:
  http:
    endpoint: "http://logging-plumber-log-aggregator.default.svc/busybox-echo/"
    buffer:
      flush_interval: 10s
      flush_mode: interval
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: cluster-busybox-echo
  namespace: cattle-logging-system
  labels:
    loggingpipelineplumber.isala.me/test: simulations
spec:
  globalOutputRefs:
    - cluster-busybox-echo
  match:
    - select:
        labels:
          loggingpipelineplumber.isala.me/test: invalid
    - select:
        labels:
          loggingpipelineplumber.isala.me/test: simulations
  filters:
    - record_modifier:
        records:
          - foo: "bar"
    - grep:
        regexp:
          - key: first
            pattern: /^5\d\d$/
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: cluster-busybox-echo
  namespace: cattle-logging-system
  labels:
    loggingpipelineplumber.isala.me/test: simulations
spec:
  http:
    endpoint: "http://logging-plumber-log-aggregator.default.svc/cluster-busybox-echo/"
    buffer:
      flush_interval: 10s
      flush_mode: interval
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-echo
  labels:
    loggingpipelineplumber.isala.me/test: simulations
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "x=1; while [ $x -gt -1 ]; do echo \"{'count': '$(( x++ ))', 'date': '$(date)'}\" && sleep 5; done"]