apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "logging-pipeline-plumber.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - clusterflows
  - clusteroutputs
  - flows
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - loggingplumber.isala.me
  resources:
  - flowtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loggingplumber.isala.me
  resources:
  - flowtests/finalizers
  verbs:
  - update
- apiGroups:
  - loggingplumber.isala.me
  resources:
  - flowtests/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "logging-pipeline-plumber.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "logging-pipeline-plumber.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "logging-pipeline-plumber.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
