apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logging-pipeline-plumber.serviceAccountName" . }}
  labels:
    {{- include "logging-pipeline-plumber.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
