name: push image

on:
  push:
    tags:
      - v*

jobs:
  build-assets:
    name: build-assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make build
      - run: docker push $CONTROLLER_IMAGE_NAME:$VERSION
      - run: docker push $SIMULATOR_IMAGE_NAME:$VERSION
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
          prerelease: ${{ env.IS_PRERELEASE }}
