name: validate

on: pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/setup-node@v2
      - run: make lint
      - run: if [ -n "$(git status --porcelain --untracked-files=no)" ]; then exit 1; fi
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build
  generate:
    name: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - run: make generate
      - run: if [ -n "$(git status --porcelain --untracked-files=no)" ]; then exit 1; fi